# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from lib.api import sys_rpc_api_pb2 as lib_dot_api_dot_sys__rpc__api__pb2
from lib.types import base_pb2 as lib_dot_types_dot_base__pb2


class YarnServiceStub(object):
    """## 调度服务 - 系统状态 接口
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNodeInfo = channel.unary_unary(
                '/rpcapi.YarnService/GetNodeInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.GetNodeInfoResponse.FromString,
                )
        self.SetSeedNode = channel.unary_unary(
                '/rpcapi.YarnService/SetSeedNode',
                request_serializer=lib_dot_api_dot_sys__rpc__api__pb2.SetSeedNodeRequest.SerializeToString,
                response_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.SetSeedNodeResponse.FromString,
                )
        self.DeleteSeedNode = channel.unary_unary(
                '/rpcapi.YarnService/DeleteSeedNode',
                request_serializer=lib_dot_api_dot_sys__rpc__api__pb2.DeleteSeedNodeRequest.SerializeToString,
                response_deserializer=lib_dot_types_dot_base__pb2.SimpleResponse.FromString,
                )
        self.GetSeedNodeList = channel.unary_unary(
                '/rpcapi.YarnService/GetSeedNodeList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.GetSeedNodeListResponse.FromString,
                )
        self.SetDataNode = channel.unary_unary(
                '/rpcapi.YarnService/SetDataNode',
                request_serializer=lib_dot_api_dot_sys__rpc__api__pb2.SetDataNodeRequest.SerializeToString,
                response_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.SetDataNodeResponse.FromString,
                )
        self.UpdateDataNode = channel.unary_unary(
                '/rpcapi.YarnService/UpdateDataNode',
                request_serializer=lib_dot_api_dot_sys__rpc__api__pb2.UpdateDataNodeRequest.SerializeToString,
                response_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.SetDataNodeResponse.FromString,
                )
        self.DeleteDataNode = channel.unary_unary(
                '/rpcapi.YarnService/DeleteDataNode',
                request_serializer=lib_dot_api_dot_sys__rpc__api__pb2.DeleteRegisteredNodeRequest.SerializeToString,
                response_deserializer=lib_dot_types_dot_base__pb2.SimpleResponse.FromString,
                )
        self.GetDataNodeList = channel.unary_unary(
                '/rpcapi.YarnService/GetDataNodeList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.GetRegisteredNodeListResponse.FromString,
                )
        self.SetJobNode = channel.unary_unary(
                '/rpcapi.YarnService/SetJobNode',
                request_serializer=lib_dot_api_dot_sys__rpc__api__pb2.SetJobNodeRequest.SerializeToString,
                response_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.SetJobNodeResponse.FromString,
                )
        self.UpdateJobNode = channel.unary_unary(
                '/rpcapi.YarnService/UpdateJobNode',
                request_serializer=lib_dot_api_dot_sys__rpc__api__pb2.UpdateJobNodeRequest.SerializeToString,
                response_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.SetJobNodeResponse.FromString,
                )
        self.DeleteJobNode = channel.unary_unary(
                '/rpcapi.YarnService/DeleteJobNode',
                request_serializer=lib_dot_api_dot_sys__rpc__api__pb2.DeleteRegisteredNodeRequest.SerializeToString,
                response_deserializer=lib_dot_types_dot_base__pb2.SimpleResponse.FromString,
                )
        self.GetJobNodeList = channel.unary_unary(
                '/rpcapi.YarnService/GetJobNodeList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.GetRegisteredNodeListResponse.FromString,
                )
        self.ReportTaskEvent = channel.unary_unary(
                '/rpcapi.YarnService/ReportTaskEvent',
                request_serializer=lib_dot_api_dot_sys__rpc__api__pb2.ReportTaskEventRequest.SerializeToString,
                response_deserializer=lib_dot_types_dot_base__pb2.SimpleResponse.FromString,
                )
        self.ReportTaskResourceUsage = channel.unary_unary(
                '/rpcapi.YarnService/ReportTaskResourceUsage',
                request_serializer=lib_dot_api_dot_sys__rpc__api__pb2.ReportTaskResourceUsageRequest.SerializeToString,
                response_deserializer=lib_dot_types_dot_base__pb2.SimpleResponse.FromString,
                )
        self.ReportUpFileSummary = channel.unary_unary(
                '/rpcapi.YarnService/ReportUpFileSummary',
                request_serializer=lib_dot_api_dot_sys__rpc__api__pb2.ReportUpFileSummaryRequest.SerializeToString,
                response_deserializer=lib_dot_types_dot_base__pb2.SimpleResponse.FromString,
                )
        self.ReportTaskResultFileSummary = channel.unary_unary(
                '/rpcapi.YarnService/ReportTaskResultFileSummary',
                request_serializer=lib_dot_api_dot_sys__rpc__api__pb2.ReportTaskResultFileSummaryRequest.SerializeToString,
                response_deserializer=lib_dot_types_dot_base__pb2.SimpleResponse.FromString,
                )
        self.QueryAvailableDataNode = channel.unary_unary(
                '/rpcapi.YarnService/QueryAvailableDataNode',
                request_serializer=lib_dot_api_dot_sys__rpc__api__pb2.QueryAvailableDataNodeRequest.SerializeToString,
                response_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.QueryAvailableDataNodeResponse.FromString,
                )
        self.QueryFilePosition = channel.unary_unary(
                '/rpcapi.YarnService/QueryFilePosition',
                request_serializer=lib_dot_api_dot_sys__rpc__api__pb2.QueryFilePositionRequest.SerializeToString,
                response_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.QueryFilePositionResponse.FromString,
                )
        self.GetTaskResultFileSummary = channel.unary_unary(
                '/rpcapi.YarnService/GetTaskResultFileSummary',
                request_serializer=lib_dot_api_dot_sys__rpc__api__pb2.GetTaskResultFileSummaryRequest.SerializeToString,
                response_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.GetTaskResultFileSummaryResponse.FromString,
                )
        self.GetTaskResultFileSummaryList = channel.unary_unary(
                '/rpcapi.YarnService/GetTaskResultFileSummaryList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.GetTaskResultFileSummaryListResponse.FromString,
                )
        self.GenerateObServerProxyWalletAddress = channel.unary_unary(
                '/rpcapi.YarnService/GenerateObServerProxyWalletAddress',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.GenerateObServerProxyWalletAddressResponse.FromString,
                )


class YarnServiceServicer(object):
    """## 调度服务 - 系统状态 接口
    """

    def GetNodeInfo(self, request, context):
        """Getter YarnNode ...
        查看自身调度服务信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSeedNode(self, request, context):
        """about seed
        新增种子节点信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSeedNode(self, request, context):
        """删除种子节点信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeedNodeList(self, request, context):
        """查询种子节点列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDataNode(self, request, context):
        """about dataNode
        新增数据服务信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDataNode(self, request, context):
        """修改数据服务信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDataNode(self, request, context):
        """删除数据服务信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDataNodeList(self, request, context):
        """查询数据服务列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetJobNode(self, request, context):
        """about jobNode
        新增计算服务信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateJobNode(self, request, context):
        """修改计算服务信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteJobNode(self, request, context):
        """删除计算服务信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobNodeList(self, request, context):
        """查询计算服务列表 (宿主机的物理信息和网络连接信息)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTaskEvent(self, request, context):
        """about report
        数据/计算服务 上报任务事件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTaskResourceUsage(self, request, context):
        """数据/计算服务 上报资源使用实况
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportUpFileSummary(self, request, context):
        """上报 成功上传的原始文件Id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTaskResultFileSummary(self, request, context):
        """上报 任务结果文件摘要
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAvailableDataNode(self, request, context):
        """查询可用数据服务资源目标 ip:port 信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryFilePosition(self, request, context):
        """查询需要下载的目标原始文件所在的 数据服务信息和文件的完整相对路径
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskResultFileSummary(self, request, context):
        """查询 任务结果文件摘要
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskResultFileSummaryList(self, request, context):
        """查询当前组织参与的所有任务结果文件摘要
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateObServerProxyWalletAddress(self, request, context):
        """v 0.4.0 生成当前组织内置系统钱包地址 (见证人代理钱包, 全局只有一个)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YarnServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNodeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=lib_dot_api_dot_sys__rpc__api__pb2.GetNodeInfoResponse.SerializeToString,
            ),
            'SetSeedNode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSeedNode,
                    request_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.SetSeedNodeRequest.FromString,
                    response_serializer=lib_dot_api_dot_sys__rpc__api__pb2.SetSeedNodeResponse.SerializeToString,
            ),
            'DeleteSeedNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSeedNode,
                    request_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.DeleteSeedNodeRequest.FromString,
                    response_serializer=lib_dot_types_dot_base__pb2.SimpleResponse.SerializeToString,
            ),
            'GetSeedNodeList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeedNodeList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=lib_dot_api_dot_sys__rpc__api__pb2.GetSeedNodeListResponse.SerializeToString,
            ),
            'SetDataNode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDataNode,
                    request_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.SetDataNodeRequest.FromString,
                    response_serializer=lib_dot_api_dot_sys__rpc__api__pb2.SetDataNodeResponse.SerializeToString,
            ),
            'UpdateDataNode': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDataNode,
                    request_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.UpdateDataNodeRequest.FromString,
                    response_serializer=lib_dot_api_dot_sys__rpc__api__pb2.SetDataNodeResponse.SerializeToString,
            ),
            'DeleteDataNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDataNode,
                    request_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.DeleteRegisteredNodeRequest.FromString,
                    response_serializer=lib_dot_types_dot_base__pb2.SimpleResponse.SerializeToString,
            ),
            'GetDataNodeList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDataNodeList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=lib_dot_api_dot_sys__rpc__api__pb2.GetRegisteredNodeListResponse.SerializeToString,
            ),
            'SetJobNode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetJobNode,
                    request_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.SetJobNodeRequest.FromString,
                    response_serializer=lib_dot_api_dot_sys__rpc__api__pb2.SetJobNodeResponse.SerializeToString,
            ),
            'UpdateJobNode': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateJobNode,
                    request_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.UpdateJobNodeRequest.FromString,
                    response_serializer=lib_dot_api_dot_sys__rpc__api__pb2.SetJobNodeResponse.SerializeToString,
            ),
            'DeleteJobNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteJobNode,
                    request_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.DeleteRegisteredNodeRequest.FromString,
                    response_serializer=lib_dot_types_dot_base__pb2.SimpleResponse.SerializeToString,
            ),
            'GetJobNodeList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobNodeList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=lib_dot_api_dot_sys__rpc__api__pb2.GetRegisteredNodeListResponse.SerializeToString,
            ),
            'ReportTaskEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTaskEvent,
                    request_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.ReportTaskEventRequest.FromString,
                    response_serializer=lib_dot_types_dot_base__pb2.SimpleResponse.SerializeToString,
            ),
            'ReportTaskResourceUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTaskResourceUsage,
                    request_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.ReportTaskResourceUsageRequest.FromString,
                    response_serializer=lib_dot_types_dot_base__pb2.SimpleResponse.SerializeToString,
            ),
            'ReportUpFileSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportUpFileSummary,
                    request_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.ReportUpFileSummaryRequest.FromString,
                    response_serializer=lib_dot_types_dot_base__pb2.SimpleResponse.SerializeToString,
            ),
            'ReportTaskResultFileSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTaskResultFileSummary,
                    request_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.ReportTaskResultFileSummaryRequest.FromString,
                    response_serializer=lib_dot_types_dot_base__pb2.SimpleResponse.SerializeToString,
            ),
            'QueryAvailableDataNode': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryAvailableDataNode,
                    request_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.QueryAvailableDataNodeRequest.FromString,
                    response_serializer=lib_dot_api_dot_sys__rpc__api__pb2.QueryAvailableDataNodeResponse.SerializeToString,
            ),
            'QueryFilePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryFilePosition,
                    request_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.QueryFilePositionRequest.FromString,
                    response_serializer=lib_dot_api_dot_sys__rpc__api__pb2.QueryFilePositionResponse.SerializeToString,
            ),
            'GetTaskResultFileSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskResultFileSummary,
                    request_deserializer=lib_dot_api_dot_sys__rpc__api__pb2.GetTaskResultFileSummaryRequest.FromString,
                    response_serializer=lib_dot_api_dot_sys__rpc__api__pb2.GetTaskResultFileSummaryResponse.SerializeToString,
            ),
            'GetTaskResultFileSummaryList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskResultFileSummaryList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=lib_dot_api_dot_sys__rpc__api__pb2.GetTaskResultFileSummaryListResponse.SerializeToString,
            ),
            'GenerateObServerProxyWalletAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateObServerProxyWalletAddress,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=lib_dot_api_dot_sys__rpc__api__pb2.GenerateObServerProxyWalletAddressResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpcapi.YarnService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class YarnService(object):
    """## 调度服务 - 系统状态 接口
    """

    @staticmethod
    def GetNodeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpcapi.YarnService/GetNodeInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            lib_dot_api_dot_sys__rpc__api__pb2.GetNodeInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSeedNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpcapi.YarnService/SetSeedNode',
            lib_dot_api_dot_sys__rpc__api__pb2.SetSeedNodeRequest.SerializeToString,
            lib_dot_api_dot_sys__rpc__api__pb2.SetSeedNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSeedNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpcapi.YarnService/DeleteSeedNode',
            lib_dot_api_dot_sys__rpc__api__pb2.DeleteSeedNodeRequest.SerializeToString,
            lib_dot_types_dot_base__pb2.SimpleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSeedNodeList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpcapi.YarnService/GetSeedNodeList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            lib_dot_api_dot_sys__rpc__api__pb2.GetSeedNodeListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDataNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpcapi.YarnService/SetDataNode',
            lib_dot_api_dot_sys__rpc__api__pb2.SetDataNodeRequest.SerializeToString,
            lib_dot_api_dot_sys__rpc__api__pb2.SetDataNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateDataNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpcapi.YarnService/UpdateDataNode',
            lib_dot_api_dot_sys__rpc__api__pb2.UpdateDataNodeRequest.SerializeToString,
            lib_dot_api_dot_sys__rpc__api__pb2.SetDataNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteDataNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpcapi.YarnService/DeleteDataNode',
            lib_dot_api_dot_sys__rpc__api__pb2.DeleteRegisteredNodeRequest.SerializeToString,
            lib_dot_types_dot_base__pb2.SimpleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDataNodeList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpcapi.YarnService/GetDataNodeList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            lib_dot_api_dot_sys__rpc__api__pb2.GetRegisteredNodeListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetJobNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpcapi.YarnService/SetJobNode',
            lib_dot_api_dot_sys__rpc__api__pb2.SetJobNodeRequest.SerializeToString,
            lib_dot_api_dot_sys__rpc__api__pb2.SetJobNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateJobNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpcapi.YarnService/UpdateJobNode',
            lib_dot_api_dot_sys__rpc__api__pb2.UpdateJobNodeRequest.SerializeToString,
            lib_dot_api_dot_sys__rpc__api__pb2.SetJobNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteJobNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpcapi.YarnService/DeleteJobNode',
            lib_dot_api_dot_sys__rpc__api__pb2.DeleteRegisteredNodeRequest.SerializeToString,
            lib_dot_types_dot_base__pb2.SimpleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJobNodeList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpcapi.YarnService/GetJobNodeList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            lib_dot_api_dot_sys__rpc__api__pb2.GetRegisteredNodeListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportTaskEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpcapi.YarnService/ReportTaskEvent',
            lib_dot_api_dot_sys__rpc__api__pb2.ReportTaskEventRequest.SerializeToString,
            lib_dot_types_dot_base__pb2.SimpleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportTaskResourceUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpcapi.YarnService/ReportTaskResourceUsage',
            lib_dot_api_dot_sys__rpc__api__pb2.ReportTaskResourceUsageRequest.SerializeToString,
            lib_dot_types_dot_base__pb2.SimpleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportUpFileSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpcapi.YarnService/ReportUpFileSummary',
            lib_dot_api_dot_sys__rpc__api__pb2.ReportUpFileSummaryRequest.SerializeToString,
            lib_dot_types_dot_base__pb2.SimpleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportTaskResultFileSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpcapi.YarnService/ReportTaskResultFileSummary',
            lib_dot_api_dot_sys__rpc__api__pb2.ReportTaskResultFileSummaryRequest.SerializeToString,
            lib_dot_types_dot_base__pb2.SimpleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryAvailableDataNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpcapi.YarnService/QueryAvailableDataNode',
            lib_dot_api_dot_sys__rpc__api__pb2.QueryAvailableDataNodeRequest.SerializeToString,
            lib_dot_api_dot_sys__rpc__api__pb2.QueryAvailableDataNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryFilePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpcapi.YarnService/QueryFilePosition',
            lib_dot_api_dot_sys__rpc__api__pb2.QueryFilePositionRequest.SerializeToString,
            lib_dot_api_dot_sys__rpc__api__pb2.QueryFilePositionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTaskResultFileSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpcapi.YarnService/GetTaskResultFileSummary',
            lib_dot_api_dot_sys__rpc__api__pb2.GetTaskResultFileSummaryRequest.SerializeToString,
            lib_dot_api_dot_sys__rpc__api__pb2.GetTaskResultFileSummaryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTaskResultFileSummaryList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpcapi.YarnService/GetTaskResultFileSummaryList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            lib_dot_api_dot_sys__rpc__api__pb2.GetTaskResultFileSummaryListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateObServerProxyWalletAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpcapi.YarnService/GenerateObServerProxyWalletAddress',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            lib_dot_api_dot_sys__rpc__api__pb2.GenerateObServerProxyWalletAddressResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
