# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: carrier/types/common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='carrier/types/common.proto',
  package='carrier.types',
  syntax='proto3',
  serialized_options=b'Z<github.com/datumtechs/datum-network-carrier/pb/carrier/types',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1a\x63\x61rrier/types/common.proto\x12\rcarrier.types\"-\n\x0eSimpleResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\tB>Z<github.com/datumtechs/datum-network-carrier/pb/carrier/typesb\x06proto3'
)




_SIMPLERESPONSE = _descriptor.Descriptor(
  name='SimpleResponse',
  full_name='carrier.types.SimpleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='carrier.types.SimpleResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='carrier.types.SimpleResponse.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['SimpleResponse'] = _SIMPLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimpleResponse = _reflection.GeneratedProtocolMessageType('SimpleResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLERESPONSE,
  '__module__' : 'carrier.types.common_pb2'
  # @@protoc_insertion_point(class_scope:carrier.types.SimpleResponse)
  })
_sym_db.RegisterMessage(SimpleResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
