# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fighter/api/via_svc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fighter/api/via_svc.proto',
  package='fighter.api',
  syntax='proto3',
  serialized_options=b'Z:github.com/datumtechs/datum-network-carrier/pb/fighter/api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x66ighter/api/via_svc.proto\x12\x0b\x66ighter.api\"t\n\tExposeReq\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12*\n\x08svc_type\x18\x02 \x01(\x0e\x32\x18.fighter.api.ServiceType\x12\x10\n\x08party_id\x18\x03 \x01(\t\x12\n\n\x02ip\x18\x04 \x01(\t\x12\x0c\n\x04port\x18\x05 \x01(\x05\"1\n\tExposeAns\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05*P\n\x0bServiceType\x12\x0c\n\x08\x44\x41TA_SVC\x10\x00\x12\x0f\n\x0b\x43OMPUTE_SVC\x10\x01\x12\x10\n\x0cSCHEDULE_SVC\x10\x02\x12\x10\n\x0cNET_COMM_SVC\x10\x03\x32\x82\x01\n\x0bViaProvider\x12:\n\x06\x45xpose\x12\x16.fighter.api.ExposeReq\x1a\x16.fighter.api.ExposeAns\"\x00\x12\x37\n\x03Off\x12\x16.fighter.api.ExposeReq\x1a\x16.fighter.api.ExposeAns\"\x00\x42<Z:github.com/datumtechs/datum-network-carrier/pb/fighter/apib\x06proto3'
)

_SERVICETYPE = _descriptor.EnumDescriptor(
  name='ServiceType',
  full_name='fighter.api.ServiceType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DATA_SVC', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMPUTE_SVC', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SCHEDULE_SVC', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NET_COMM_SVC', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=211,
  serialized_end=291,
)
_sym_db.RegisterEnumDescriptor(_SERVICETYPE)

ServiceType = enum_type_wrapper.EnumTypeWrapper(_SERVICETYPE)
DATA_SVC = 0
COMPUTE_SVC = 1
SCHEDULE_SVC = 2
NET_COMM_SVC = 3



_EXPOSEREQ = _descriptor.Descriptor(
  name='ExposeReq',
  full_name='fighter.api.ExposeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='fighter.api.ExposeReq.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='svc_type', full_name='fighter.api.ExposeReq.svc_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='party_id', full_name='fighter.api.ExposeReq.party_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip', full_name='fighter.api.ExposeReq.ip', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='fighter.api.ExposeReq.port', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=158,
)


_EXPOSEANS = _descriptor.Descriptor(
  name='ExposeAns',
  full_name='fighter.api.ExposeAns',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='fighter.api.ExposeAns.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip', full_name='fighter.api.ExposeAns.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='fighter.api.ExposeAns.port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=209,
)

_EXPOSEREQ.fields_by_name['svc_type'].enum_type = _SERVICETYPE
DESCRIPTOR.message_types_by_name['ExposeReq'] = _EXPOSEREQ
DESCRIPTOR.message_types_by_name['ExposeAns'] = _EXPOSEANS
DESCRIPTOR.enum_types_by_name['ServiceType'] = _SERVICETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExposeReq = _reflection.GeneratedProtocolMessageType('ExposeReq', (_message.Message,), {
  'DESCRIPTOR' : _EXPOSEREQ,
  '__module__' : 'fighter.api.via_svc_pb2'
  # @@protoc_insertion_point(class_scope:fighter.api.ExposeReq)
  })
_sym_db.RegisterMessage(ExposeReq)

ExposeAns = _reflection.GeneratedProtocolMessageType('ExposeAns', (_message.Message,), {
  'DESCRIPTOR' : _EXPOSEANS,
  '__module__' : 'fighter.api.via_svc_pb2'
  # @@protoc_insertion_point(class_scope:fighter.api.ExposeAns)
  })
_sym_db.RegisterMessage(ExposeAns)


DESCRIPTOR._options = None

_VIAPROVIDER = _descriptor.ServiceDescriptor(
  name='ViaProvider',
  full_name='fighter.api.ViaProvider',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=294,
  serialized_end=424,
  methods=[
  _descriptor.MethodDescriptor(
    name='Expose',
    full_name='fighter.api.ViaProvider.Expose',
    index=0,
    containing_service=None,
    input_type=_EXPOSEREQ,
    output_type=_EXPOSEANS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Off',
    full_name='fighter.api.ViaProvider.Off',
    index=1,
    containing_service=None,
    input_type=_EXPOSEREQ,
    output_type=_EXPOSEANS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VIAPROVIDER)

DESCRIPTOR.services_by_name['ViaProvider'] = _VIAPROVIDER

# @@protoc_insertion_point(module_scope)
