# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lib/common.proto',
  package='common',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10lib/common.proto\x12\x06\x63ommon\"A\n\x05Party\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x10\n\x08party_id\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\"\xba\x03\n\x0eTaskReadyGoReq\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08party_id\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x61ta_id\x18\x03 \x01(\t\x12\x0e\n\x06\x65nv_id\x18\x04 \x01(\t\x12\x1e\n\x07parties\x18\x05 \x03(\x0b\x32\r.common.Party\x12\x16\n\x0e\x61lgorithm_code\x18\x06 \x01(\t\x12\x34\n\x12\x61lgorithm_cfg_type\x18\x07 \x01(\x0e\x32\x18.common.AlgorithmCfgType\x12\x15\n\ralgorithm_cfg\x18\x08 \x01(\t\x12\x12\n\ndata_party\x18\t \x03(\t\x12\x19\n\x11\x63omputation_party\x18\n \x03(\t\x12\x14\n\x0cresult_party\x18\x0b \x03(\t\x12\x10\n\x08\x64uration\x18\x0c \x01(\x04\x12\x0e\n\x06memory\x18\r \x01(\x04\x12\x11\n\tprocessor\x18\x0e \x01(\r\x12\x11\n\tbandwidth\x18\x0f \x01(\x04\x12:\n\x15\x63onnect_policy_format\x18\x10 \x01(\x0e\x32\x1b.common.ConnectPolicyFormat\x12\x16\n\x0e\x63onnect_policy\x18\x11 \x01(\t\"+\n\x10TaskReadyGoReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\"2\n\rTaskCancelReq\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08party_id\x18\x02 \x01(\t\"*\n\x0fTaskCancelReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t*Q\n\x10\x41lgorithmCfgType\x12\x1c\n\x18\x41lgorithmCfgType_2DTable\x10\x00\x12\x1f\n\x1b\x41lgorithmCfgType_non2DTable\x10\x01*P\n\x13\x43onnectPolicyFormat\x12\x1b\n\x17\x43onnectPolicyFormat_Str\x10\x00\x12\x1c\n\x18\x43onnectPolicyFormat_Json\x10\x01\x62\x06proto3'
)

_ALGORITHMCFGTYPE = _descriptor.EnumDescriptor(
  name='AlgorithmCfgType',
  full_name='common.AlgorithmCfgType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AlgorithmCfgType_2DTable', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AlgorithmCfgType_non2DTable', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=681,
  serialized_end=762,
)
_sym_db.RegisterEnumDescriptor(_ALGORITHMCFGTYPE)

AlgorithmCfgType = enum_type_wrapper.EnumTypeWrapper(_ALGORITHMCFGTYPE)
_CONNECTPOLICYFORMAT = _descriptor.EnumDescriptor(
  name='ConnectPolicyFormat',
  full_name='common.ConnectPolicyFormat',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ConnectPolicyFormat_Str', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ConnectPolicyFormat_Json', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=764,
  serialized_end=844,
)
_sym_db.RegisterEnumDescriptor(_CONNECTPOLICYFORMAT)

ConnectPolicyFormat = enum_type_wrapper.EnumTypeWrapper(_CONNECTPOLICYFORMAT)
AlgorithmCfgType_2DTable = 0
AlgorithmCfgType_non2DTable = 1
ConnectPolicyFormat_Str = 0
ConnectPolicyFormat_Json = 1



_PARTY = _descriptor.Descriptor(
  name='Party',
  full_name='common.Party',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='common.Party.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='common.Party.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='party_id', full_name='common.Party.party_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='common.Party.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=93,
)


_TASKREADYGOREQ = _descriptor.Descriptor(
  name='TaskReadyGoReq',
  full_name='common.TaskReadyGoReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='common.TaskReadyGoReq.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='party_id', full_name='common.TaskReadyGoReq.party_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_id', full_name='common.TaskReadyGoReq.data_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='env_id', full_name='common.TaskReadyGoReq.env_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parties', full_name='common.TaskReadyGoReq.parties', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algorithm_code', full_name='common.TaskReadyGoReq.algorithm_code', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algorithm_cfg_type', full_name='common.TaskReadyGoReq.algorithm_cfg_type', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algorithm_cfg', full_name='common.TaskReadyGoReq.algorithm_cfg', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_party', full_name='common.TaskReadyGoReq.data_party', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='computation_party', full_name='common.TaskReadyGoReq.computation_party', index=9,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result_party', full_name='common.TaskReadyGoReq.result_party', index=10,
      number=11, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration', full_name='common.TaskReadyGoReq.duration', index=11,
      number=12, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='memory', full_name='common.TaskReadyGoReq.memory', index=12,
      number=13, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='processor', full_name='common.TaskReadyGoReq.processor', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bandwidth', full_name='common.TaskReadyGoReq.bandwidth', index=14,
      number=15, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connect_policy_format', full_name='common.TaskReadyGoReq.connect_policy_format', index=15,
      number=16, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connect_policy', full_name='common.TaskReadyGoReq.connect_policy', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=538,
)


_TASKREADYGOREPLY = _descriptor.Descriptor(
  name='TaskReadyGoReply',
  full_name='common.TaskReadyGoReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='common.TaskReadyGoReply.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='common.TaskReadyGoReply.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=540,
  serialized_end=583,
)


_TASKCANCELREQ = _descriptor.Descriptor(
  name='TaskCancelReq',
  full_name='common.TaskCancelReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='common.TaskCancelReq.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='party_id', full_name='common.TaskCancelReq.party_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=585,
  serialized_end=635,
)


_TASKCANCELREPLY = _descriptor.Descriptor(
  name='TaskCancelReply',
  full_name='common.TaskCancelReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='common.TaskCancelReply.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='common.TaskCancelReply.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=637,
  serialized_end=679,
)

_TASKREADYGOREQ.fields_by_name['parties'].message_type = _PARTY
_TASKREADYGOREQ.fields_by_name['algorithm_cfg_type'].enum_type = _ALGORITHMCFGTYPE
_TASKREADYGOREQ.fields_by_name['connect_policy_format'].enum_type = _CONNECTPOLICYFORMAT
DESCRIPTOR.message_types_by_name['Party'] = _PARTY
DESCRIPTOR.message_types_by_name['TaskReadyGoReq'] = _TASKREADYGOREQ
DESCRIPTOR.message_types_by_name['TaskReadyGoReply'] = _TASKREADYGOREPLY
DESCRIPTOR.message_types_by_name['TaskCancelReq'] = _TASKCANCELREQ
DESCRIPTOR.message_types_by_name['TaskCancelReply'] = _TASKCANCELREPLY
DESCRIPTOR.enum_types_by_name['AlgorithmCfgType'] = _ALGORITHMCFGTYPE
DESCRIPTOR.enum_types_by_name['ConnectPolicyFormat'] = _CONNECTPOLICYFORMAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Party = _reflection.GeneratedProtocolMessageType('Party', (_message.Message,), {
  'DESCRIPTOR' : _PARTY,
  '__module__' : 'lib.common_pb2'
  # @@protoc_insertion_point(class_scope:common.Party)
  })
_sym_db.RegisterMessage(Party)

TaskReadyGoReq = _reflection.GeneratedProtocolMessageType('TaskReadyGoReq', (_message.Message,), {
  'DESCRIPTOR' : _TASKREADYGOREQ,
  '__module__' : 'lib.common_pb2'
  # @@protoc_insertion_point(class_scope:common.TaskReadyGoReq)
  })
_sym_db.RegisterMessage(TaskReadyGoReq)

TaskReadyGoReply = _reflection.GeneratedProtocolMessageType('TaskReadyGoReply', (_message.Message,), {
  'DESCRIPTOR' : _TASKREADYGOREPLY,
  '__module__' : 'lib.common_pb2'
  # @@protoc_insertion_point(class_scope:common.TaskReadyGoReply)
  })
_sym_db.RegisterMessage(TaskReadyGoReply)

TaskCancelReq = _reflection.GeneratedProtocolMessageType('TaskCancelReq', (_message.Message,), {
  'DESCRIPTOR' : _TASKCANCELREQ,
  '__module__' : 'lib.common_pb2'
  # @@protoc_insertion_point(class_scope:common.TaskCancelReq)
  })
_sym_db.RegisterMessage(TaskCancelReq)

TaskCancelReply = _reflection.GeneratedProtocolMessageType('TaskCancelReply', (_message.Message,), {
  'DESCRIPTOR' : _TASKCANCELREPLY,
  '__module__' : 'lib.common_pb2'
  # @@protoc_insertion_point(class_scope:common.TaskCancelReply)
  })
_sym_db.RegisterMessage(TaskCancelReply)


# @@protoc_insertion_point(module_scope)
