# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from lib import via_svc_pb2 as lib_dot_via__svc__pb2


class ViaProviderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Expose = channel.unary_unary(
                '/viasvc.ViaProvider/Expose',
                request_serializer=lib_dot_via__svc__pb2.ExposeReq.SerializeToString,
                response_deserializer=lib_dot_via__svc__pb2.ExposeAns.FromString,
                )
        self.Off = channel.unary_unary(
                '/viasvc.ViaProvider/Off',
                request_serializer=lib_dot_via__svc__pb2.ExposeReq.SerializeToString,
                response_deserializer=lib_dot_via__svc__pb2.ExposeAns.FromString,
                )


class ViaProviderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Expose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Off(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ViaProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Expose': grpc.unary_unary_rpc_method_handler(
                    servicer.Expose,
                    request_deserializer=lib_dot_via__svc__pb2.ExposeReq.FromString,
                    response_serializer=lib_dot_via__svc__pb2.ExposeAns.SerializeToString,
            ),
            'Off': grpc.unary_unary_rpc_method_handler(
                    servicer.Off,
                    request_deserializer=lib_dot_via__svc__pb2.ExposeReq.FromString,
                    response_serializer=lib_dot_via__svc__pb2.ExposeAns.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'viasvc.ViaProvider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ViaProvider(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Expose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/viasvc.ViaProvider/Expose',
            lib_dot_via__svc__pb2.ExposeReq.SerializeToString,
            lib_dot_via__svc__pb2.ExposeAns.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Off(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/viasvc.ViaProvider/Off',
            lib_dot_via__svc__pb2.ExposeReq.SerializeToString,
            lib_dot_via__svc__pb2.ExposeAns.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
