# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fighter/types/types.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.constant import fighter_enum_pb2 as common_dot_constant_dot_fighter__enum__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fighter/types/types.proto',
  package='fighter.types',
  syntax='proto3',
  serialized_options=b'Z<github.com/datumtechs/datum-network-carrier/pb/fighter/types',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x66ighter/types/types.proto\x12\rfighter.types\x1a\"common/constant/fighter_enum.proto\"A\n\x05Party\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x10\n\x08party_id\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\"\xb3\x03\n\x0eTaskReadyGoReq\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08party_id\x18\x02 \x01(\t\x12\x0e\n\x06\x65nv_id\x18\x03 \x01(\t\x12%\n\x07parties\x18\x04 \x03(\x0b\x32\x14.fighter.types.Party\x12\x16\n\x0e\x61lgorithm_code\x18\x05 \x01(\t\x12\x17\n\x0fself_cfg_params\x18\x06 \x01(\t\x12 \n\x18\x61lgorithm_dynamic_params\x18\x07 \x01(\t\x12\x16\n\x0e\x64\x61ta_party_ids\x18\x08 \x03(\t\x12\x1d\n\x15\x63omputation_party_ids\x18\t \x03(\t\x12\x18\n\x10result_party_ids\x18\n \x03(\t\x12\x10\n\x08\x64uration\x18\x0b \x01(\x04\x12\x0e\n\x06memory\x18\x0c \x01(\x04\x12\x11\n\tprocessor\x18\r \x01(\r\x12\x11\n\tbandwidth\x18\x0e \x01(\x04\x12\x43\n\x15\x63onnect_policy_format\x18\x0f \x01(\x0e\x32$.common.constant.ConnectPolicyFormat\x12\x16\n\x0e\x63onnect_policy\x18\x10 \x01(\t\"/\n\x10TaskReadyGoReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"2\n\rTaskCancelReq\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08party_id\x18\x02 \x01(\t\".\n\x0fTaskCancelReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\tB>Z<github.com/datumtechs/datum-network-carrier/pb/fighter/typesb\x06proto3'
  ,
  dependencies=[common_dot_constant_dot_fighter__enum__pb2.DESCRIPTOR,])




_PARTY = _descriptor.Descriptor(
  name='Party',
  full_name='fighter.types.Party',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='fighter.types.Party.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='fighter.types.Party.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='party_id', full_name='fighter.types.Party.party_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='fighter.types.Party.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=145,
)


_TASKREADYGOREQ = _descriptor.Descriptor(
  name='TaskReadyGoReq',
  full_name='fighter.types.TaskReadyGoReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='fighter.types.TaskReadyGoReq.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='party_id', full_name='fighter.types.TaskReadyGoReq.party_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='env_id', full_name='fighter.types.TaskReadyGoReq.env_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parties', full_name='fighter.types.TaskReadyGoReq.parties', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algorithm_code', full_name='fighter.types.TaskReadyGoReq.algorithm_code', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='self_cfg_params', full_name='fighter.types.TaskReadyGoReq.self_cfg_params', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algorithm_dynamic_params', full_name='fighter.types.TaskReadyGoReq.algorithm_dynamic_params', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_party_ids', full_name='fighter.types.TaskReadyGoReq.data_party_ids', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='computation_party_ids', full_name='fighter.types.TaskReadyGoReq.computation_party_ids', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result_party_ids', full_name='fighter.types.TaskReadyGoReq.result_party_ids', index=9,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration', full_name='fighter.types.TaskReadyGoReq.duration', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='memory', full_name='fighter.types.TaskReadyGoReq.memory', index=11,
      number=12, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='processor', full_name='fighter.types.TaskReadyGoReq.processor', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bandwidth', full_name='fighter.types.TaskReadyGoReq.bandwidth', index=13,
      number=14, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connect_policy_format', full_name='fighter.types.TaskReadyGoReq.connect_policy_format', index=14,
      number=15, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connect_policy', full_name='fighter.types.TaskReadyGoReq.connect_policy', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=583,
)


_TASKREADYGOREPLY = _descriptor.Descriptor(
  name='TaskReadyGoReply',
  full_name='fighter.types.TaskReadyGoReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='fighter.types.TaskReadyGoReply.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='fighter.types.TaskReadyGoReply.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=585,
  serialized_end=632,
)


_TASKCANCELREQ = _descriptor.Descriptor(
  name='TaskCancelReq',
  full_name='fighter.types.TaskCancelReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='fighter.types.TaskCancelReq.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='party_id', full_name='fighter.types.TaskCancelReq.party_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=634,
  serialized_end=684,
)


_TASKCANCELREPLY = _descriptor.Descriptor(
  name='TaskCancelReply',
  full_name='fighter.types.TaskCancelReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='fighter.types.TaskCancelReply.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='fighter.types.TaskCancelReply.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=686,
  serialized_end=732,
)

_TASKREADYGOREQ.fields_by_name['parties'].message_type = _PARTY
_TASKREADYGOREQ.fields_by_name['connect_policy_format'].enum_type = common_dot_constant_dot_fighter__enum__pb2._CONNECTPOLICYFORMAT
DESCRIPTOR.message_types_by_name['Party'] = _PARTY
DESCRIPTOR.message_types_by_name['TaskReadyGoReq'] = _TASKREADYGOREQ
DESCRIPTOR.message_types_by_name['TaskReadyGoReply'] = _TASKREADYGOREPLY
DESCRIPTOR.message_types_by_name['TaskCancelReq'] = _TASKCANCELREQ
DESCRIPTOR.message_types_by_name['TaskCancelReply'] = _TASKCANCELREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Party = _reflection.GeneratedProtocolMessageType('Party', (_message.Message,), {
  'DESCRIPTOR' : _PARTY,
  '__module__' : 'fighter.types.types_pb2'
  # @@protoc_insertion_point(class_scope:fighter.types.Party)
  })
_sym_db.RegisterMessage(Party)

TaskReadyGoReq = _reflection.GeneratedProtocolMessageType('TaskReadyGoReq', (_message.Message,), {
  'DESCRIPTOR' : _TASKREADYGOREQ,
  '__module__' : 'fighter.types.types_pb2'
  # @@protoc_insertion_point(class_scope:fighter.types.TaskReadyGoReq)
  })
_sym_db.RegisterMessage(TaskReadyGoReq)

TaskReadyGoReply = _reflection.GeneratedProtocolMessageType('TaskReadyGoReply', (_message.Message,), {
  'DESCRIPTOR' : _TASKREADYGOREPLY,
  '__module__' : 'fighter.types.types_pb2'
  # @@protoc_insertion_point(class_scope:fighter.types.TaskReadyGoReply)
  })
_sym_db.RegisterMessage(TaskReadyGoReply)

TaskCancelReq = _reflection.GeneratedProtocolMessageType('TaskCancelReq', (_message.Message,), {
  'DESCRIPTOR' : _TASKCANCELREQ,
  '__module__' : 'fighter.types.types_pb2'
  # @@protoc_insertion_point(class_scope:fighter.types.TaskCancelReq)
  })
_sym_db.RegisterMessage(TaskCancelReq)

TaskCancelReply = _reflection.GeneratedProtocolMessageType('TaskCancelReply', (_message.Message,), {
  'DESCRIPTOR' : _TASKCANCELREPLY,
  '__module__' : 'fighter.types.types_pb2'
  # @@protoc_insertion_point(class_scope:fighter.types.TaskCancelReply)
  })
_sym_db.RegisterMessage(TaskCancelReply)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
